/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marketplace.repository.entity.dynamo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * @author Martin Pilar mpilarcastillejo@gmail.com
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ddb-telemetria-energia-dev")
public class TelemetriaEnergiaEntity {

    @DynamoDBHashKey(attributeName = "idrequest")
//    @DynamoDBAutoGeneratedKey
    private String idRequest;
    @DynamoDBAttribute(attributeName = "device")
    private String device;
    @DynamoDBAttribute(attributeName = "fecregistro")
    private String fecRegistro;
    @DynamoDBAttribute(attributeName = "data_calculation")
    private String dataCalculation;
    @DynamoDBAttribute(attributeName = "idcliente")
    private String idCliente;
    @DynamoDBAttribute(attributeName = "payload")
    private String payload;
}
